# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f788c4c9af5045342387954703e5481763bb410209f1155dacfe971ffca9526fff7ca1c924954ae4b56c7378f1ab01b9aaf119687aaeb8c4aa94174834ce686

test:
  secret_key_base: 3423eca4e61dccfa7ec0df7a2728ebe8669a53b0bc7034f353fb6032ba6fccb518de2e4c65b0fc1ca694029d0f57e78fbe86b3f563791c593aa834f89ef7043b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
